services:
    db:
        image: mongo:latest
        container_name: db
        env_file:
            - .env
        ports:
            - '${DB_PORT}:27017'
        volumes:
            - dbdata-volume:/data/db
        environment:
            MONGO_INITDB_USERNAME: ${DB_USERNAME}
            MONGO_INITDB_PASSWORD: ${DB_PASSWORD}
            MONGO_INITDB_DATABASE: ${DB_DATABASE}
        networks:
            - app-network
        restart: always
    api:
        container_name: api
        build: .
        env_file:
            - .env
        volumes:
            - .:/usr/src/app
            - /usr/src/app/node_modules
        depends_on:
            - db
        links:
            - db
        networks:
            - app-network
        ports:
            - ${APP_PORT}:${APP_PORT}
        command: npm run start
        restart: always
networks:
    app-network:
        driver: bridge
volumes:
    dbdata-volume: