openapi: 3.0.0
info:
  title: Example API
  description: API with Bearer Token Authentication
  version: 1.0.0
servers:
  - url: http://api.example.com/v1
components:
  securitySchemes:
    BearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
security:
  - BearerAuth: []
paths:
  /example:
    get:
      summary: Example endpoint
      security:
        - BearerAuth: []
      responses:
        '200':
          description: Successful response
        '401':
          description: Unauthorized