name: Node.js CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x, 20.x, 22.x]

    steps:
    - uses: actions/checkout@v4

    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}

    - run: npm ci

    - run: npm run build --if-present

    - run: npm test

  deploy:
    runs-on: ubuntu-latest
    needs: build
    if: github.ref == 'refs/heads/main'

    steps:
    - uses: actions/checkout@v4

    - name: Set up Heroku CLI
      run: |
        curl https://cli-assets.heroku.com/install.sh | sh
        heroku --version

    - name: Log in to Heroku
      env:
        HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}
      run: |
        echo $HEROKU_API_KEY | heroku auth:token

    - name: Add Heroku Remote
      run: |
        git remote -v

      run: |
        git remote add heroku https://git.heroku.com/gptuserapi.git

    - name: Deploy to Heroku
      run: |
        git push heroku main
